name: Safe Systems Logstash
description: |
    Logstash Message Parser
version: v0.1
category: Message Parsing
maintainer: Reid Riley <reid.riley@safesystems.com>
projectURL: http://www.safesystems.com
